defmodule DemoRepo.Repo.Migrations.AddEntities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:entities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :size, :float
      add :balance, :money_with_currency
    end
  end

  def down do
    drop table(:entities)
  end
end
